name = "cdn-worker"
main = "src/index.ts"
compatibility_date = "2023-11-21"

account_id = "d6ece11a8138144bc6c0de0dc2cc4784"
workers_dev = true
compatibility_flags = [ "nodejs_compat" ]

[vars]
JWT_SECRET = "Rubw4ZVY3G%7"
IDENTIFY_KEY = "FriendZone"

[[r2_buckets]]

binding = 'BUCKET'
bucket_name = 'friend-zone'
preview_bucket_name = 'friend-zone'